title: Enjoy Our Life
description: A project towards a better life
theme: just-the-docs

url: https://ericize.github.io/ericize

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
